services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
  consul:
    container_name: consul
    image: hashicorp/consul
    ports:
      - "8500:8500"