services:
  postgres:
    container_name: wiu-postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
  consul:
    container_name: wiu-consul
    image: hashicorp/consul
    ports:
      - "8500:8500"
  mailhog:
    container_name: wiu-mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  keycloak:
    container_name: wiu-keycloak
    image: quay.io/keycloak/keycloak:24.0.4
    volumes:
#      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/import:/opt/keycloak/data/import
    command: start-dev --import-realm
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin