spring:
  application:
    name: wiu_post_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wiu_user}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:user}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/writeitup}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8090/realms/writeitup/protocol/openid-connect/certs}
server:
  port: 8083

keycloak:
  realm: ${KEYCLOAK_REALM:writeitup}
  server-url: ${KEYCLOAK_URL:http://localhost:8090/}
  client-id: ${KEYCLOAK_CLIENT_ID:wiu_backend}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:secret}