server:
  port: 8081

spring:
  application:
    name: wiu_gateway_service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: ${CONSUL_IP_PREFERENCE:true}
        service-name: ${spring.application.name}
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
            allowed-headers:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
              - HEAD
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: wiu-post-service
          uri: lb://wiu-post-service
          predicates:
            - Path=/api/v1/posts/**
        - id: wiu-user-service
          uri: lb://wiu-user-service
          predicates:
            - Path=/api/v1/users/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS