server:
  port: 8081

spring:
  application:
    name: wiu_gateway_service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: ${CONSUL_IP_PREFERENCE:true}
        service-name: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS