spring:
  application:
    name: wiu_post_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wiu_post}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:user}
  liquibase:
    change-log: db/changelog/master.xml
    default-schema: public
    liquibase-schema: public
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: ${CONSUL_IP_PREFERENCE:true}
        service-name: ${spring.application.name}
  # To be removed
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: com.writeitup.wiu_post_service.config.CustomPostgreSQLDialect
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
