spring:
  application:
    name: wiu_post_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wiu_post}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:user}
  liquibase:
    change-log: db/changelog/master.xml
    default-schema: public
    liquibase-schema: public
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: ${CONSUL_IP_PREFERENCE:true}
        service-name: ${spring.application.name}
  jpa:
    database-platform: com.writeitup.wiu_post_service.config.CustomPostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/writeitup}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8090/realms/writeitup/protocol/openid-connect/certs}
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
